document.write('<ul class="menu" id="menu">')
	document.write('<li><a href="/index.html" class="menulink">Home</a></li>')
	document.write('<li><a href="/program/summer/summer_camp.html" class="menulink">Summer Camp</a>')
		document.write('<ul>')
			document.write('<li><a href="/register/register.html">REGISTER NOW</a></li>')
			document.write('<li><a href="/register/forms.html">Camp Forms</a></li>')
			document.write('<li><a href="/Documents/Summer Registration/2011 Campership Discount Request Form.pdf">Scholarship Application</a></li>')
			document.write('<li><a href="/program/summer/summer_camp.html#SummerSchedule" class="sub">Summer Schedule</a>')
				document.write('<ul>')
					document.write('<li><a href="/program/summer/specialfriends.html">Special Friends</a></li>')
					document.write('<li><a href="/program/summer/CIT_Program.html">Leadership (CIT)</a></li>')
					document.write('<li><a href="/program/summer/adventures.html">Adventures on the Coast</a></li>')
					document.write('<li><a href="/program/summer/servants.html">Servant Events</a></li>')
					document.write('<li><a href="/program/summer/shalom.html">SHALOM Camp</a></li>')
				document.write('</ul>')
			document.write('</li>')
			document.write('<li><a href="/program/summer/day_camp.html" class="sub">Day Camp</a>')
				document.write('<ul>')
					document.write('<li><a href="/program/summer/day_camp_schedule.html">2012 Calendar</a>')
					document.write('<li><a href="/program/summer/day_camp_resources.html">Resources</a></li>')
				document.write('</ul>')
			document.write('</li>')
			document.write('<li><a href="#" class="sub">Adult Volunteers</a>')
				document.write('<ul>')
					document.write('<li><a href="/program/summer/pastor_in_residence.html" class="topline">Summer Pastor</a></li>')
					document.write('<li><a href="/program/summer/nurse.html">Summer Camp Nurse</a></li>')
				document.write('</ul>')
			document.write('</li>')
		document.write('</ul>')
	document.write('</li>')
	document.write('<li><a href="/retreats.html" class="menulink">Year Round Programs</a>')
		document.write('<ul>')
			document.write('<li><a href="/program/education_fall.html">Fall Outdoor Education</a></li>')
			document.write('<li><a href="/program/retreats/jrhigh.html" class="sub">Jr. High Retreats</a>')
				document.write('<ul>')
					document.write('<li><a href="/program/retreats/jrhigh_JAM.html">JAM</a></li>')
					document.write('<li><a href="/program/retreats/jrhigh_EoY.html">[EoY] End of the Year</a></li>')
				document.write('</ul>')
	document.write('</li>')
			document.write('<li><a href="/program/retreats/youth_ski.html" class="sub">Youth Ski Retreat</a></li>')
			document.write('<li><a href="/program/retreats/adults.html" class="sub">Adult Retreats</a>')
				document.write('<ul>')
					document.write('<li><a href="/program/retreats/adults_women.html">Fall Womens Retreat</a></li>')
					document.write('<li><a href="/program/retreats/adults_men.html">Spring Mens Retreat</a></li>')
				document.write('</ul>')
				
			document.write('</li>')
			document.write('<li><a href="/program/retreats/family.html" class="sub">Family Retreats</a>')
				document.write('<ul>')
					document.write('<li><a href="/program/retreats/family_memorialdayworkweekend.html">Family Work Weekend</a></li>')
				document.write('</ul>')
			document.write('</li>')
			document.write('<li><a href="/ChallengeCourse.html">Challenge Course</a></li>')
			document.write('<li><a href="/rentals.html">Plan  Your Own Retreat</a></li>')
		document.write('</ul>')
	document.write('</li>')
	document.write('<li><a href="/rentals.html" class="menulink">Group Rentals</a>')
		document.write('<ul>')
			document.write('<li><a href="/rentals/availability.html">Availability</a></li>')
			document.write('<li><a href="/rentals/facilities.html" class="sub">Facilities</a>')
				document.write('<ul>')
					document.write('<li><a href="/rentals/facilities_oak.html">Oak Lodge</a></li>')
					document.write('<li><a href="/rentals/facilities_lowerjensen.html">Jensen Lodge</a></li>')
					document.write('<li><a href="/rentals/facilities_evergreen.html">Evergreen Dorm</a></li>')
					document.write('<li><a href="/rentals/facilities_redwood.html">Redwood Dorm</a></li>')
					document.write('<li><a href="/rentals/facilities_madrones.html">Madrone Cabins</a></li>')
				document.write('</ul>')
			document.write('</li>')
			document.write('<li><a href="/ChallengeCourse.html">Challenge Course</a></li>')
		document.write('</ul>')
	document.write('</li>')
	document.write('<li><a href="/donations/onlinegiving.html" class="menulink">Donate</a>')
		document.write('<ul>')
			document.write('<li><a href="/donations/onlinegiving.html">Donate Online</a></li>')
			document.write('<li><a href="/donations/bigtreeclub.html">Big Tree Club</a></li>')
			document.write('<li><a href="/donations/plannedgiving.html">Planned Giving</a></li>')
			document.write('<li><a href="/donations/endowment.html">Endowment Fund</a></li>')
			document.write('<li><a href="/donations/campership.html">Campership Fund</a></li>')
			document.write('<li><a href="/donations/inkind.html">Inkind Giving</a></li>')
			document.write('<li><a href="/donations/Thrivent.html">Thrivent</a></li>')
			document.write('<li><a href="/donations/annual_reports.html">Annual Reports</a></li>')
		document.write('</ul>')
	document.write('</li>')
	document.write('<li><a href="" class="menulink">About Us</a>')
		document.write('<ul>')
			document.write('<li><a href="/about/contact.html" class="sub">Contact Us</a>')
				document.write('<ul class="right">')
					document.write('<li><a href="/about/staff.html">Staff</a></li>')
					document.write('<li><a href="/about/directors.html">Board of Directors</a></li>')
				document.write('</ul>')
			document.write('</li>')
			document.write('<li><a href="/about/causes.html">Our Causes</a></li>')
			document.write('<li><a href="/about/employment.html" class="sub">Employment</a>')
				document.write('<ul class="right">')
					document.write('<li><a href="/about/employment_summer.html">Summer Ministry Staff</a></li>')
					document.write('<li><a href="/about/employment_yearround.html">Year-Round Staff</a></li>')
				document.write('</ul>')
			document.write('</li>')
			document.write('<li><a href="/donations/inkind_volunteers.html" class="sub">Volunteer</a>')
				document.write('<ul class="right">')
					document.write('<li><a href="/about/directors_committees_rangers.html">Rangers</a></li>')
					document.write('<li><a href="/program/summer/pastor_in_residence.html">Summer Pastor</a></li>')
					document.write('<li><a href="/program/summer/nurse.html">Summer Camp Nurse</a></li>')
				document.write('</ul>')
			document.write('</li>')
			document.write('<li><a href="/about/history/page_1.html">History</a></li>')
			document.write('<li><a href="/about/alumni.html">Alumni</a></li>')
			document.write('<li><a href="/about/directions.html">Directions & Maps</a></li>')
			document.write('<li><a href="/about/camp_map.html">Interactive Camp Map</a></li>')
		document.write('</ul>')
	document.write('</li>')
document.write('</ul>');



document.write('<script type="text/javascript">')
	document.write('var menu=new menu.dd("menu");')
	document.write('menu.init("menu","menuhover");')
document.write('</script>');


